version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: pan_kyc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: pan_kyc_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    depends_on:
      - backend

volumes:
  postgres_data:
